name: UAT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to UAT
        env:
          REACT_APP_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          echo "REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}" > .env.production
          echo "API_ENDPOINT=${API_ENDPOINT}" >> .env.production
          echo "VITE_API_URL=${VITE_API_URL}" >> .env.production
          npm run build
          npm run preview
